- id: shfmt
  name: shfmt
  description: Shell source code formatter (native install)
  language: system
  entry: shfmt -w -s
  types: [shell]
  stages: [commit, merge-commit, push, manual]
- id: shellcheck
  name: ShellCheck
  description: Static analysis tool for shell scripts
  language: system
  entry: shellcheck
  types: [shell]
